# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from lib.grpc.dockerInfo_pb2 import *


class DockerInfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DockerInfo = channel.unary_unary(
                '/DockerInfo/DockerInfo',
                request_serializer=DockerInfoRequest.SerializeToString,
                response_deserializer=DockerInfoResponse.FromString,
                )
        self.ExecuteUpdate = channel.unary_unary(
                '/DockerInfo/ExecuteUpdate',
                request_serializer=DockerInfoRequest.SerializeToString,
                response_deserializer=DockerInfoResponse.FromString,
                )


class DockerInfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DockerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DockerInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DockerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.DockerInfo,
                    request_deserializer=DockerInfoRequest.FromString,
                    response_serializer=DockerInfoResponse.SerializeToString,
            ),
            'ExecuteUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteUpdate,
                    request_deserializer=DockerInfoRequest.FromString,
                    response_serializer=DockerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DockerInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DockerInfo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DockerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DockerInfo/DockerInfo',
            DockerInfoRequest.SerializeToString,
           DockerInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DockerInfo/ExecuteUpdate',
            DockerInfoRequest.SerializeToString,
            DockerInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
